version: '2.4'
services:
  devops_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
    restart: on-failure
  redis:
    image: "redis:alpine"  
    ports:
      - 6379:6379

