{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
spec:
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.appName }}
              servicePort: 80
{{ end }}
